import { useRef } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Download, Printer } from "lucide-react";
import { useBusiness } from "@/hooks/use-business";

export type PaymentRow = {
  id: string;
  reference: string;
  plan: string;
  amount_kobo: number;
  currency: string;
  status: string;
  provider: string;
  verified_at: string | null;
  created_at: string;
  raw: any;
};

export const PLAN_CREDITS: Record<string, number> = {
  growth: 7000,
  business: 20000,
};

interface Props {
  payment: PaymentRow | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

const fmtNaira = (kobo: number) =>
  `₦${(kobo / 100).toLocaleString("en-NG", { minimumFractionDigits: 0 })}`;

export default function PaymentReceiptDialog({ payment, open, onOpenChange }: Props) {
  const receiptRef = useRef<HTMLDivElement>(null);
  const { logoUrl, businessName } = useBusiness();

  if (!payment) return null;

  const credits = PLAN_CREDITS[payment.plan] ?? 0;
  const paidAt = payment.verified_at ?? payment.created_at;
  const dateStr = new Date(paidAt).toLocaleString("en-NG", {
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
  const receiptNo = `RCP-${payment.reference}`;
  const channel = payment.raw?.channel ?? "—";
  const payerEmail = payment.raw?.customer?.email ?? "—";
  const statusClass =
    payment.status === "success" ? "status-paid" : payment.status === "pending" ? "status-pending" : "status-failed";

  const buildHtml = () => `
    <html><head><meta charset="utf-8" /><title>Receipt ${receiptNo}</title>
    <style>
      body { font-family: system-ui, -apple-system, sans-serif; padding: 40px; color: #1a1a1a; max-width: 680px; margin: 0 auto; }
      .head { display:flex; justify-content:space-between; align-items:flex-start; border-bottom:2px solid #e5e7eb; padding-bottom:20px; margin-bottom:24px; }
      .biz { font-size:18px; font-weight:700; }
      .muted { color:#6b7280; font-size:12px; }
      .title { font-size:24px; font-weight:800; color:#6366f1; text-align:right; }
      table { width:100%; border-collapse:collapse; margin:20px 0; }
      th { background:#f9fafb; text-align:left; padding:10px 12px; font-size:11px; text-transform:uppercase; color:#6b7280; border-bottom:2px solid #e5e7eb; }
      td { padding:11px 12px; border-bottom:1px solid #f3f4f6; font-size:14px; }
      .total td { font-weight:700; font-size:16px; border-top:2px solid #e5e7eb; border-bottom:none; }
      .status { display:inline-block; padding:3px 10px; border-radius:999px; font-size:11px; font-weight:600; text-transform:capitalize; }
      .status-paid { background:#dcfce7; color:#16a34a; }
      .status-pending { background:#fef3c7; color:#d97706; }
      .status-failed { background:#fee2e2; color:#dc2626; }
      .footer { margin-top:36px; padding-top:16px; border-top:1px solid #e5e7eb; font-size:11px; color:#9ca3af; text-align:center; }
      @media print { body { padding: 20px; } }
    </style></head><body>
      <div class="head">
        <div style="display:flex;gap:12px;align-items:center">
          ${logoUrl ? `<img src="${logoUrl}" style="width:56px;height:56px;border-radius:12px;object-fit:cover" />` : ""}
          <div><div class="biz">${businessName}</div><div class="muted">Powered by ManyFlow</div></div>
        </div>
        <div style="text-align:right">
          <div class="title">RECEIPT</div>
          <div class="muted">${receiptNo}</div>
          <div class="muted">${dateStr}</div>
        </div>
      </div>
      <div style="margin-bottom:8px" class="muted">PAYMENT DETAILS</div>
      <table>
        <tr><th>Field</th><th>Value</th></tr>
        <tr><td>Reference</td><td>${payment.reference}</td></tr>
        <tr><td>Provider</td><td>${payment.provider}</td></tr>
        <tr><td>Channel</td><td>${channel}</td></tr>
        <tr><td>Billed email</td><td>${payerEmail}</td></tr>
        <tr><td>Status</td><td><span class="status ${statusClass}">${payment.status}</span></td></tr>
        <tr><td>Plan</td><td style="text-transform:capitalize">${payment.plan}</td></tr>
        <tr><td>Credits added</td><td>${credits.toLocaleString()} credits</td></tr>
        <tr class="total"><td>Amount paid</td><td>${fmtNaira(payment.amount_kobo)} ${payment.currency}</td></tr>
      </table>
      <div class="footer">This receipt was generated by ManyFlow for ${businessName}.</div>
    </body></html>`;

  const handlePrint = () => {
    const win = window.open("", "_blank");
    if (!win) return;
    win.document.write(buildHtml());
    win.document.close();
    win.focus();
    win.print();
  };

  const handleDownload = () => {
    const blob = new Blob([buildHtml()], { type: "text/html;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${receiptNo}.html`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const Row = ({ label, value }: { label: string; value: React.ReactNode }) => (
    <div className="flex items-center justify-between py-2 border-b last:border-0 gap-4">
      <span className="text-xs text-muted-foreground">{label}</span>
      <span className="text-xs sm:text-sm font-medium text-right break-all">{value}</span>
    </div>
  );

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-lg max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="text-base">Payment receipt</DialogTitle>
        </DialogHeader>

        <div ref={receiptRef} className="rounded-lg border p-4">
          <div className="flex items-start justify-between mb-3 pb-3 border-b">
            <div className="flex items-center gap-2.5">
              {logoUrl ? (
                <img src={logoUrl} alt={`${businessName} logo`} className="h-11 w-11 rounded-lg object-cover" />
              ) : (
                <div className="h-11 w-11 rounded-lg bg-muted flex items-center justify-center font-bold">
                  {businessName.charAt(0)}
                </div>
              )}
              <div>
                <p className="font-heading font-semibold text-sm">{businessName}</p>
                <p className="text-[10px] text-muted-foreground">Powered by ManyFlow</p>
              </div>
            </div>
            <div className="text-right">
              <p className="font-heading font-bold text-primary">RECEIPT</p>
              <p className="text-[10px] text-muted-foreground break-all">{receiptNo}</p>
            </div>
          </div>

          <Row label="Date" value={dateStr} />
          <Row label="Reference" value={payment.reference} />
          <Row label="Provider" value={payment.provider} />
          <Row label="Channel" value={channel} />
          <Row label="Status" value={<span className="capitalize">{payment.status}</span>} />
          <Row label="Plan" value={<span className="capitalize">{payment.plan}</span>} />
          <Row label="Credits added" value={`${credits.toLocaleString()} credits`} />
          <Row
            label="Amount paid"
            value={<span className="font-bold">{fmtNaira(payment.amount_kobo)} {payment.currency}</span>}
          />
        </div>

        <div className="flex gap-2">
          <Button variant="outline" size="sm" className="flex-1 gap-2" onClick={handlePrint}>
            <Printer className="h-4 w-4" /> Print / Save PDF
          </Button>
          <Button size="sm" className="flex-1 gap-2" onClick={handleDownload}>
            <Download className="h-4 w-4" /> Download
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
